CREATE SCHEMA IF NOT EXISTS CarGoApplication;
USE CarGoApplication;

DROP TABLE IF EXISTS Messages;
DROP TABLE IF EXISTS Reviews;
DROP TABLE IF EXISTS Saves;
DROP TABLE IF EXISTS Cars;
DROP TABLE IF EXISTS Searches;
DROP TABLE IF EXISTS Companies;
DROP TABLE IF EXISTS Sellers;
DROP TABLE IF EXISTS Buyers;
DROP TABLE IF EXISTS Admins;
DROP TABLE IF EXISTS Users;


CREATE TABLE Companies (
 CompanyId INT AUTO_INCREMENT,
 CompanyName VARCHAR(255),
 Description VARCHAR(1023),
 CONSTRAINT pk_Companies_CompanyId PRIMARY KEY (CompanyId)
);

CREATE TABLE Users (
 UserId INT AUTO_INCREMENT,
 FirstName VARCHAR(255) NOT NULL,
 LastName VARCHAR(255) NOT NULL,
 Email VARCHAR(255) NOT NULL,
 Password VARCHAR(255) NOT NULL,
 CONSTRAINT pk_Users_UserId PRIMARY KEY (UserId),
 CONSTRAINT uq_Users_Email UNIQUE(Email)
);

CREATE TABLE Admins (
 UserId INT,
 CONSTRAINT pk_Admins_UserId PRIMARY KEY (UserId),
 CONSTRAINT fk_Admins_UserId FOREIGN KEY (UserId)
  REFERENCES Users(UserId)
  ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Buyers (
 BuyerId INT,
 DOB DATE NOT NULL,
 ZIP INT NOT NULL,
 CONSTRAINT pk_Admins_BuyerId PRIMARY KEY (BuyerId),
 CONSTRAINT fk_Admins_BuyerId FOREIGN KEY (BuyerId)
  REFERENCES Users(UserId)
  ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Sellers (
 SellerId INT,
 CompanyId INT,
 ZIP INT NOT NULL,
 Address VARCHAR(255) NOT NULL,
 Introduction VARCHAR(1023),
 CONSTRAINT pk_Sellers_SellerId PRIMARY KEY (SellerId),
 CONSTRAINT fk_Sellers_SellerId FOREIGN KEY (SellerId)
  REFERENCES Users(UserId)
  ON UPDATE CASCADE ON DELETE CASCADE,
 CONSTRAINT fk_Sellers_CompanyId FOREIGN KEY (CompanyId)
  REFERENCES Companies(CompanyId)
  ON UPDATE CASCADE ON DELETE SET NULL
);
